import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ['thai', 'latin'],
  weight: ['300', '400', '500', '700'], // เลือก weight ที่ต้องการ
  display: 'swap',
  variable: '--font-kanit', // ตัวแปร CSS สำหรับใช้ใน style
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
